# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: WebApiName
    displayName: "WebAPI Name. (e.g.: BlogWebAPI)"
    type: string
    default: Hack3rLife

  - name: RepoName
    displayName: "Repository Name"
    type: string
    default: dotnet-webapi
  
  - name: Email
    displayName: "Github Email"
    type: string
    default: hack3rlifeio@gmail.com

  - name: UserName
    displayName: "Github UserName"
    type: string
    default: hack3rlife
    
  - name: Organization
    displayName: "Azure DevOps organization URL"
    type: string

  - name: Project
    displayName: "Name or ID of the project"
    type: string
  
  - name: AZURE_PAT
    displayName: "Azure DevOps Personal Access Token"
    type: string 
    
steps:
- script: echo Creating a new WebAPI for ${{parameters.WebApiName}}!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'new'
    arguments: '--install Hack3rlife.ASP.NETCore.WebAPI'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'new'
    arguments: 'CleanArchitectureNetCoreWebAPI -n ${{parameters.WebApiName}} -o tmp --force'
- task: CmdLine@2
  inputs:
    script: |        
        echo ${{parameters.AZURE_PAT}} | az devops login --org ${{parameters.Organization}}

        az repos create --name ${{parameters.RepoName}} --org ${{parameters.Organization}} --project ${{parameters.Project}}

        cd tmp
        git init -b main
        git config --global user.email "${{parameters.Email}}"
        git config --global user.name "${{parameters.UserName}}"
        git add .
        git commit -m "Initial Commit"

        git remote add origin https://${{parameters.UserName}}:${{parameters.AZURE_PAT}}@dev.azure.com/${{parameters.UserName}}/${{parameters.Project}}/_git/${{parameters.RepoName}}
        
        git push -f -u origin main

        cd ..
        rmdir tmp -v --ignore-fail-on-non-empty

        az pipelines create --name ${{parameters.RepoName}} --repository ${{ parameters.RepoName }} --project ${{parameters.Project}} --yml-path '/azure-pipelines.yml' --repository-type tfsgit --branch main --skip-first-run

