# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: Name
    displayName: "WebAPI Name. (e.g.: BlogWebAPI)"
    type: string

steps:
- script: echo Creating a new WebAPI for ${{parameters.name}}!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'new'
    arguments: '--install Hack3rlife.ASP.NETCore.WebAPI'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'new'
    arguments: 'CleanArchitectureNetCoreWebAPI -n tmp\${{parameters.name}} --force'


