# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: WebApiName
    displayName: "WebAPI Name. (e.g.: BlogWebAPI)"
    type: string

  - name: RepoName
    displayName: "Repository Name"
    type: string
  
  - name: Email
    displayName: "WebAPI Name. (e.g.: BlogWebAPI)"
    type: string

  - name: UserName
    displayName: "WebAPI Name. (e.g.: BlogWebAPI)"
    type: string
steps:
- script: echo Creating a new WebAPI for ${{parameters.WebApiName}}!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'new'
    arguments: '--install Hack3rlife.ASP.NETCore.WebAPI'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'new'
    arguments: 'CleanArchitectureNetCoreWebAPI -n ${{parameters.WebApiName}} -o tmp --force'

- task: CmdLine@2
  inputs:
    script: |
      cd tmp
      git init
      git config --global user.email "${{parameters.Email}}"
      git config --global user.name "${{parameters.UserName}}"
      git remote add origin git@github.com:hack3rlife/${{parameters.RepoName}}.git
      git add .
      git commit -m "First Commit"
      git push -u origin main




